# Generated by Django 2.2.2 on 2019-06-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('sciper', models.IntegerField(primary_key=True, serialize=False, verbose_name='EPFL sciper')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('role', models.CharField(choices=[('teacher', 'teacher'), ('teaching assistant', 'teaching assistant')], default='teacher', max_length=255)),
            ],
            options={
                'ordering': ('lastName', 'firstName'),
            },
        ),
    ]
