# Generated by Django 2.2.2 on 2019-06-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
