# Generated by Django 2.2.2 on 2019-06-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('term', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('numberOfStudents', models.IntegerField()),
            ],
        ),
    ]
