# Generated by Django 2.2.2 on 2019-06-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(through='web.Teaching', to='web.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='courses',
            field=models.ManyToManyField(through='web.Teaching', to='web.Course'),
        ),
    ]
