# Generated by Django 2.2.2 on 2019-06-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190623_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sciper',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
