# Generated by Django 2.2.2 on 2019-06-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190617_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('year', 'term', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('year', 'term', 'code')},
        ),
        migrations.AlterIndexTogether(
            name='course',
            index_together={('year', 'term', 'code')},
        ),
    ]
