# Generated by Django 2.2.2 on 2019-06-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_person_sciper'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='has_exercises',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='has_practical_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='has_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='taughtInGerman',
            field=models.BooleanField(default=False),
        ),
    ]
