# Generated by Django 2.2.2 on 2019-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190701_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='taughtInFrench',
            field=models.BooleanField(default=False),
        ),
    ]
