# Generated by Django 2.2.2 on 2019-06-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190617_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='approvedNumberOfTAs',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='calculatedNumberOfTAs',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='previousYearNumberOfTAs',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
