# Generated by Django 2.2.2 on 2019-07-09 12:34

from django.db import migrations, models
import web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190704_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.CharField(max_length=9, validators=[web.validators.validate_year_config])),
                ('current_term', models.CharField(choices=[('WINTER', 'Hiver'), ('SUMMER', 'Eté')], max_length=6)),
                ('requests_for_TAs_are_open', models.BooleanField(default=True)),
                ('applications_are_open', models.BooleanField(default=True)),
            ],
        ),
    ]
