# Generated by Django 2.2.2 on 2019-07-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='send_notification_to_admins_upon_ta_request',
            field=models.BooleanField(default=True),
        ),
    ]
