# Generated by Django 2.2.2 on 2019-07-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_config_send_notification_to_admins_upon_ta_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='current_term',
            field=models.CharField(choices=[('HIVER', 'HIVER'), ('ETE', 'ETE')], max_length=6),
        ),
    ]
