# Generated by Django 2.2.2 on 2019-06-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberoftaupdaterequest',
            name='requestedNumberOfTAs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('person', 'course')},
        ),
        migrations.AddIndex(
            model_name='teaching',
            index=models.Index(fields=['person'], name='sciper_idx'),
        ),
        migrations.AddIndex(
            model_name='teaching',
            index=models.Index(fields=['course'], name='course_idx'),
        ),
    ]
