# Generated by Django 2.2.2 on 2019-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190618_0842'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='course',
            index_together={('year', 'term'), ('year', 'term', 'code')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['year'], name='year_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='code_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['section'], name='section_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['taughtInFrench'], name='french_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['taughtInFrench'], name='english_idx'),
        ),
    ]
