# Generated by Django 2.2.2 on 2019-09-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190717_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='applications_withdrawn',
            field=models.IntegerField(default=0),
        ),
    ]
