# Generated by Django 2.2.2 on 2019-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_course_applications_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='phds_can_withdraw_applications',
            field=models.BooleanField(default=True),
        ),
    ]
