# Generated by Django 2.2.2 on 2019-06-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190618_0848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interests',
            unique_together={('person', 'topic')},
        ),
    ]
