# Generated by Django 2.2.2 on 2019-06-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190618_0850'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interests',
            index=models.Index(fields=['person'], name='web_interes_person__0f8833_idx'),
        ),
        migrations.AddIndex(
            model_name='interests',
            index=models.Index(fields=['topic'], name='web_interes_topic_i_dd4aa0_idx'),
        ),
    ]
