# Generated by Django 2.2.2 on 2019-09-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_config_phds_can_withdraw_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='source',
            field=models.CharField(default='web', max_length=255),
        ),
    ]
