# Generated by Django 2.2.7 on 2019-11-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_applications_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='role',
            field=models.CharField(default='TA', max_length=255),
        ),
    ]
