# Generated by Django 2.2.2 on 2019-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20190618_0855'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='numberoftaupdaterequest',
            index=models.Index(fields=['requester'], name='web_numbero_request_5ed5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='numberoftaupdaterequest',
            index=models.Index(fields=['course'], name='web_numbero_course__a48ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='numberoftaupdaterequest',
            index=models.Index(fields=['status'], name='web_numbero_status_7a9a98_idx'),
        ),
    ]
