# Generated by Django 2.2.2 on 2019-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20190618_0857'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='applications',
            index=models.Index(fields=['applicant'], name='web_applica_applica_5662b3_idx'),
        ),
        migrations.AddIndex(
            model_name='applications',
            index=models.Index(fields=['course'], name='web_applica_course__0cd6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='applications',
            index=models.Index(fields=['status'], name='web_applica_status_731f1f_idx'),
        ),
    ]
