# Generated by Django 2.2.7 on 2019-12-09 14:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_availability_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('year', models.CharField(max_length=9)),
                ('term', models.CharField(choices=[('winter', 'winter'), ('summer', 'summer')], max_length=255)),
                ('activity_type', models.CharField(choices=[('code', 'Human readable'), ('class teaching', 'Class teaching'), ('master thesis', 'Master thesis'), ('semester project', 'Semester project'), ('MAN', 'MAN'), ('other job', 'Other job'), ('not available', 'Not available'), ('nothing to report', 'Nothing to report')], max_length=255)),
                ('master_thesis_year', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Year of the thesis')),
                ('master_thesis_term', models.CharField(blank=True, choices=[('winter', 'winter'), ('summer', 'summer')], default=None, max_length=255, null=True, verbose_name='Term of the thesis')),
                ('master_thesis_title', models.TextField(blank=True, default=None, null=True, verbose_name='Title of the Master thesis')),
                ('master_thesis_student_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name of the student')),
                ('master_thesis_supervision_hours', models.IntegerField(blank=True, default=None, null=True, verbose_name='Number of hours of supervision')),
                ('master_thesis_comments', models.TextField(blank=True, null=True, verbose_name='Comments regarding the master thesis activity')),
                ('master_thesis_section', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name="Teacher's section")),
                ('master_thesis_other_section', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Other section (if the section is not found in the previous list)')),
                ('class_teaching_preparation_hours', models.IntegerField(blank=True, default=None, null=True, verbose_name='Total number of preparation hours for class teaching for the semester')),
                ('class_teaching_teaching_hours', models.IntegerField(blank=True, default=None, null=True, verbose_name='Total number of teaching hours (courses and exercises over the semester)')),
                ('class_teaching_practical_work_hours', models.IntegerField(blank=True, default=None, null=True, verbose_name='Total number of practical work hours (over the semester)')),
                ('class_teaching_comments', models.TextField(blank=True, default=None, null=True, verbose_name='Comments regarding the class teaching activity')),
                ('semester_project_year', models.CharField(blank=True, default=None, max_length=9, null=True, verbose_name='Academic year of the semester project')),
                ('semester_project_term', models.CharField(blank=True, choices=[('winter', 'winter'), ('summer', 'summer')], default=None, max_length=255, null=True, verbose_name='Term of the semester project')),
                ('semester_project_thesis_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ttitle of the thesis')),
                ('semester_project_student_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name of the student')),
                ('semester_project_supervision_hours', models.IntegerField(blank=True, default=None, null=True, verbose_name='Total number of supervision hours (over the semester)')),
                ('semester_project_comments', models.TextField(blank=True, default=None, null=True, verbose_name='Comments regarding the semester project activity')),
                ('other_job_year', models.CharField(blank=True, default=None, max_length=9, null=True, verbose_name='Academic year of the other job')),
                ('other_job_term', models.CharField(blank=True, choices=[('winter', 'winter'), ('summer', 'summer')], default=None, max_length=255, null=True, verbose_name='Term of the other job')),
                ('other_job_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name of the activity')),
                ('other_job_unit', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name of the unit asking for this other job')),
                ('other_job_hours', models.IntegerField(blank=True, default=None, null=True, verbose_name='Total number of hours spent on the other job (over the semester)')),
                ('other_job_comments', models.TextField(blank=True, default=None, null=True, verbose_name="Comments regarding the 'other job' activity")),
                ('nothing_to_report_comments', models.TextField(blank=True, default=None, null=True, verbose_name="Comments regarding the 'nothing to report' activity")),
                ('not_available_comments', models.TextField(blank=True, default=None, null=True, verbose_name="Comments regarding the 'not available' activity")),
                ('MAN_year', models.CharField(blank=True, default=None, max_length=9, null=True, verbose_name='Academic year of the MAN')),
                ('MAN_term', models.CharField(blank=True, choices=[('winter', 'winter'), ('summer', 'summer')], default=None, max_length=255, null=True, verbose_name='Term of MAN')),
                ('MAN_hours', models.IntegerField(blank=True, default=None, null=True, verbose_name='Total number of hours spent on MAN (over the semester)')),
                ('MAN_comments', models.TextField(blank=True, default=None, null=True, verbose_name='Comments regarding the MAN activity')),
                ('class_teaching_course', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Course', verbose_name='Class teaching course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('master_thesis_teacher_in_charge', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervised_master_thesis', to=settings.AUTH_USER_MODEL, verbose_name='Teacher supervising the thesis')),
                ('other_job_teacher_in_charge', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervised_other_job', to=settings.AUTH_USER_MODEL, verbose_name='Teacher supervising the other job')),
                ('semester_project_teacher_in_charge', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervised_semester_projects', to=settings.AUTH_USER_MODEL, verbose_name='Teacher supervising the thesis')),
            ],
        ),
    ]
