# Generated by Django 2.2.2 on 2019-06-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20190618_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='previousYearNumberOfTAs',
            new_name='requestedNumberOfTAs',
        ),
    ]
