# Generated by Django 3.0 on 2019-12-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_timereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timereport',
            name='activity_type',
            field=models.CharField(choices=[('class teaching', 'Class teaching'), ('master thesis', 'Master thesis'), ('semester project', 'Semester project'), ('MAN', 'MAN'), ('other job', 'Other job'), ('not available', 'Not available'), ('nothing to report', 'Nothing to report')], max_length=255),
        ),
        migrations.AlterField(
            model_name='timereport',
            name='master_thesis_section',
            field=models.CharField(blank=True, choices=[('SGM', 'SGM'), ('SEL', 'SEL'), ('SMT', 'SMT'), ('SMX', 'SMX'), ('other', 'other')], default=None, max_length=255, null=True, verbose_name="Teacher's section"),
        ),
        migrations.AlterField(
            model_name='timereport',
            name='master_thesis_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Title of the Master thesis'),
        ),
    ]
