# Generated by Django 3.0.2 on 2020-01-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20200117_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timereport',
            name='master_thesis_other_section',
        ),
        migrations.RemoveField(
            model_name='timereport',
            name='master_thesis_section',
        ),
    ]
