# Generated by Django 3.0.2 on 2020-01-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_timereport_class_teaching_exam_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='timereport',
            name='exam_proctoring_and_grading_comments',
            field=models.TextField(blank=True, default=None, null=True, verbose_name="Comments regarding the 'exam proctoring and grading' activity"),
        ),
        migrations.AddField(
            model_name='timereport',
            name='exam_proctoring_and_grading_course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proctored_course', to='web.Course', verbose_name='Exam proctoring and grading course'),
        ),
        migrations.AddField(
            model_name='timereport',
            name='exam_proctoring_and_grading_hours',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Total number of hours spent on the exam proctoring and grading (over the semester)'),
        ),
        migrations.AlterField(
            model_name='timereport',
            name='activity_type',
            field=models.CharField(choices=[('class teaching', 'Class teaching'), ('master thesis', 'Master thesis'), ('semester project', 'Semester project'), ('MAN', 'MAN'), ('other job', 'Other job'), ('not available', 'Not available'), ('nothing to report', 'Nothing to report'), ('exam proctoring and grading', 'exam proctoring and grading')], max_length=255),
        ),
    ]
