# Generated by Django 3.0.2 on 2020-01-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20200123_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='time_reporting_is_open',
            field=models.BooleanField(default=False),
        ),
    ]
