# Generated by Django 3.0.2 on 2020-01-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_config_time_reporting_is_open'),
        ('web', '0016_auto_20191219_1613'),
    ]

    operations = [
    ]
