# Generated by Django 3.0.2 on 2020-03-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_merge_20200124_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursebook_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Custom URL to coursebook'),
        ),
    ]
