# Generated by Django 3.1b1 on 2020-08-18 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20200818_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail_campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('to', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in-progress', 'in-progress'), ('successfully finished', 'successfully finished'), ('finished with errors', 'finished with errors')], default='pending', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mail campaign',
                'verbose_name_plural': 'mail campaigns',
            },
        ),
        migrations.CreateModel(
            name='Mail_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('to', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('error', 'error')], default='pending', max_length=255)),
                ('error_message', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mail_campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mail message',
                'verbose_name_plural': 'mail messages',
            },
        ),
    ]
