# Generated by Django 3.1 on 2020-08-22 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_mail_campaign_mail_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_campaign',
            name='do_not_send_before',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
