# Generated by Django 3.1.3 on 2020-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_mail_campaign_do_not_send_before'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
